### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by map0logo** [ErudioOne/NumPy#3]
> Make the materials CC BY-NC-ND 4.0 (https://creativecommons.org/licenses/by-nc-nd/4.0/)

**Comment by DavidMertz** [comment]
I've put in the LICENSE.md file in the repo as a whole. Do you think we should stick in the "CC BY-NC-ND 4.0" one liner in each individual notebook?

**Comment by map0logo** [comment]
These are the subtleties of licensing, in technical terms, putting the license in the root folder and making the repository public is enough, because in a code repository the "work" is the application or library. But in the case of educational content, the "work" can be any of the lessons.

In The Carpentries, they leave a link to the license in the footer. So I recommend to include the license in every Jupyter notebook, I think a template can be designed to avoid this being too repetitive and to make sure it always appears.

**Comment by DavidMertz** [comment]
Good idea, I agree.  Let's put the notice on each notebook.  It's pretty unobtrusive. Maybe just one line below the company logo on each NB.

I'm friends with Greg Wilson, whom I really like and admire, and love the Carpentries.  I've worked with him when I create the Anaconda training program, but I was never a Software Carpentry directly (nor Data Carpentry, etc).
